<?php

declare(strict_types=1);

namespace App\Tests\App\Controller;

use Symfony\Component\HttpClient\Response\MockResponse;

class FrameworksControllerTest extends AbstractControllerTestCase
{
    /**
     * Tests that requests with Bot User-Agents are immediately rejected.
     */
    public function testListEndpointBlocksBotsAndThrowsAccessDenied()
    {
        $this->client->request('GET', '/agreements/1', [], [], [
            'HTTP_USER_AGENT' => 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)'
        ]);
        
        $this->assertResponseStatusCodeSame(403);
    }

    /**
     * Tests that legacy category slugs are automatically 302 redirected to their modern equivalents.
     */
    public function testListEndpointRedirectsOldCategorySlugs()
    {
        $this->client->request('GET', '/agreements/1', ['category' => 'utilities-fuels']);
        
        // Match the exact query string array wrapper generated by Symfony
        $this->assertResponseRedirects('/agreements?category%5B0%5D=Energy');
    }

    /**
     * Tests the hardcoded redirect for the CAS agreement.
     */
    public function testShowEndpointRedirectsCasAgreement()
    {
        $this->client->request('GET', '/agreements/RM6187_cas');
        
        $this->assertResponseRedirects('/agreements/RM6187');
    }

    /**
     * Tests that the framework show endpoint successfully renders the page using fixture data.
     */
    public function testShowEndpointRendersFrameworkSuccessfully()
    {
        // 1. Load and decode your raw JSON fixture
        $fixturePath = __DIR__ . '/../../Fixtures/frameworks_show.json';
        $this->assertFileExists($fixturePath, "Whoops! Cannot find fixture at: " . $fixturePath);
        
        $fixtureJson = file_get_contents($fixturePath);
        $frameworkData = json_decode($fixtureJson, true);

        // 2. Pass the decoded array straight into our factory
        $mockContent = \App\Tests\App\Mock\CMSContentMockFactory::createMockContent($frameworkData);

        // 3. Mock the Page object to return our factory content
        $mockPage = $this->createMock(\Strata\Frontend\Content\Page::class);
        $mockPage->method('getContent')->willReturn($mockContent);

        // 4. Build the Mock Chain for the ContentModel
        $mockContentType = $this->createMock(\Strata\Frontend\ContentModel\ContentType::class);
        $mockContentModel = $this->createMock(\Strata\Frontend\ContentModel\ContentModel::class);
        $mockContentModel->method('getContentType')->willReturn($mockContentType);

        // 5. Create the RestData mock
        $mockRestData = $this->createMock(\Strata\Frontend\Cms\RestData::class);
        $mockRestData->method('getContentModel')->willReturn($mockContentModel);
        $mockRestData->method('getOne')->willReturn($mockPage); 

        // 6. Inject the RestData API mock into the container
        // (ControllerHelper mock is now handled automatically by services_test.yaml!)
        static::getContainer()->set('app.test.rest_data_api', $mockRestData);

        // 8. Dispatch the request to the show endpoint for RM6184
        $this->client->request('GET', '/agreements/RM6184');

        // 9. Run your assertions
        $this->assertResponseIsSuccessful();
        
        $html = $this->client->getResponse()->getContent();
        
        // Assert that the page rendered the specific data from our fixture!
        $this->assertStringContainsString('RM6184', $html);
        $this->assertStringContainsString('Offsite Construction Solutions', $html);
        $this->assertStringContainsString('PCR15 Framework', $html);
    }
  /**
     * Tests that the lot suppliers endpoint compiles data into a downloadable CSV attachment.
     */
    public function testSuppliersOnLotCsvGeneratesTextAttachment()
    {
        $supplierData = [
            'supplier_name'          => 'Acme Corp',
            'supplier_trading_name'  => 'Acme Trading',
            'supplier_contact_name'  => 'Wile E. Coyote',
            'supplier_contact_email' => 'wile@acme.com',
            'supplier_street'        => '123 Desert Road',
            'supplier_city'          => 'Canyon',
            'supplier_postcode'      => 'AC1 1ME'
        ];

        // 1. Create the content using our own factory
        $mockContent = \App\Tests\App\Mock\CMSContentMockFactory::createMockContent($supplierData);

        // 2. Create a mock of the strict Page class and return our factory content
        $mockPage = $this->createMock(\Strata\Frontend\Content\Page::class);
        $mockPage->method('getContent')->willReturn($mockContent);

        // 3. Create a mock Pagination object required by the collection constructor
        $mockPagination = $this->createMock(\Strata\Frontend\Content\Pagination\PaginationInterface::class);

        // 4. Instantiate the REAL PageCollection and use its native addItem() method
        $realCollection = new \Strata\Frontend\Content\PageCollection($mockPagination);
        $realCollection->addItem($mockPage);

        // 5. Build the Mock Chain for the ContentModel
        $mockContentType = $this->createMock(\Strata\Frontend\ContentModel\ContentType::class);
        $mockContentModel = $this->createMock(\Strata\Frontend\ContentModel\ContentModel::class);
        $mockContentModel->method('getContentType')->willReturn($mockContentType);

        // 6. Create a type-safe PHPUnit mock of RestData
        $mockRestData = $this->createMock(\Strata\Frontend\Cms\RestData::class);
        
        // 7. Stub the internal method calls so the controller doesn't hit a null pointer
        $mockRestData->method('getContentModel')->willReturn($mockContentModel);
        $mockRestData->method('list')->willReturn($realCollection);

        // 8. Inject the mock RestData into the test container
        static::getContainer()->set('app.test.rest_data_api', $mockRestData);

        // 9. Dispatch the CSV request
        $this->client->request('GET', '/agreements/RM123:1/lot-suppliers/csv');

        $this->assertResponseIsSuccessful();
        $this->assertResponseHeaderSame('Content-Type', 'text/plain; charset=UTF-8');
        $this->assertResponseHeaderSame('Content-Disposition', 'attachment; filename="RM123_Lot1.csv";');

        // Extract and verify contents
        $csvContent = $this->client->getResponse()->getContent();
        $this->assertStringContainsString('"Supplier Name","Trading Name"', $csvContent);
        $this->assertStringContainsString('"Acme Corp","Acme Trading"', $csvContent);
    }

  /**
     * Tests that the framework list endpoint successfully renders the page using the JSON fixture.
     */
    public function testListEndpointRendersFrameworksSuccessfully()
    {
        // 1. Load and decode your list fixture
        $fixturePath = __DIR__ . '/../../Fixtures/frameworks_list.json';
        $this->assertFileExists($fixturePath, "Cannot find fixture at: " . $fixturePath);
        
        $fixtureJson = file_get_contents($fixturePath);
        $apiData = json_decode($fixtureJson, true);

        // 2. Mock the Pagination object using the "meta" data from your JSON
        $mockPagination = $this->createMock(\Strata\Frontend\Content\Pagination\PaginationInterface::class);
        $mockPagination->method('getTotalResults')->willReturn($apiData['meta']['total_results']);
        
        // Return 1 so Twig skips the includes/pagination.html.twig file and avoids the crash!
        $mockPagination->method('getTotalPages')->willReturn(1); // 248 results / 20 per page

        // 3. Instantiate the REAL PageCollection
        $realCollection = new \Strata\Frontend\Content\PageCollection($mockPagination);

        // 4. Loop through the "results" array in your JSON and create a mock Page for each framework
        foreach ($apiData['results'] as $frameworkData) {
            // NOTE: If your test crashes on "format() on string", you will need to update your 
            // CMSContentMockFactory to convert 'start_date' and 'end_date' into \DateTime objects!
            $mockContent = \App\Tests\App\Mock\CMSContentMockFactory::createMockContent($frameworkData);
            
            $mockPage = $this->createMock(\Strata\Frontend\Content\Page::class);
            $mockPage->method('getContent')->willReturn($mockContent);
            
            $realCollection->addItem($mockPage);
        }

        // 5. Build the ContentType & ContentModel mocks
        $mockContentType = $this->createMock(\Strata\Frontend\ContentModel\ContentType::class);
        $mockContentModel = $this->createMock(\Strata\Frontend\ContentModel\ContentModel::class);
        $mockContentModel->method('getContentType')->willReturn($mockContentType);

        // 6. Mock the SEARCH API (RestData)
        $mockSearchApi = $this->createMock(\Strata\Frontend\Cms\RestData::class);
        $mockSearchApi->method('getContentModel')->willReturn($mockContentModel);
        $mockSearchApi->method('getContentType')->willReturn($mockContentType); 
        
        // Return our fixture-populated collection!
        $mockSearchApi->method('list')->willReturn($realCollection); 

        // 7. Inject the mock into the container (Targeting the search API)
        static::getContainer()->set('app.test.rest_data_search_api', $mockSearchApi);

        // 8. Dispatch the request to the list endpoint
        $this->client->request('GET', '/agreements');

        // 9. Run your assertions
        $this->assertResponseIsSuccessful();
        
        $html = $this->client->getResponse()->getContent();
        
        // Assert the total results span is rendered (from list.html.twig)
        $this->assertStringContainsString('248 agreements found', $html);

        // Assert that the _resultWithoutJS.html.twig fallback correctly rendered the items from your JSON!
        
        // Checking for the first result (RM6348):
        $this->assertStringContainsString('RM6348', $html);
        $this->assertStringContainsString('Adult Skills and Learning DPS', $html);
        $this->assertStringContainsString('Dynamic Purchasing System', $html);
        
        // Checking for the second result (RM6102):
        $this->assertStringContainsString('RM6102', $html);
        $this->assertStringContainsString('Apprenticeship Training Dynamic Marketplace', $html);
    }

      /**
     * Tests that the upcoming deals page renders successfully with content from the HTTP API.
     */
    public function testUpcomingDealsPageRendersSuccessfully()
    {
        $this->mockHttpClient->setResponseFactory(function () {
            return new MockResponse(json_encode([
                'upcomingDealsInfo' => [
                    'title' => 'Upcoming agreements overview',
                    'page_description' => '<p>Find upcoming procurements here.</p>',
                    'file' => '/files/pipeline-report.pdf'
                ],
                'table_4' => ['title' => 'Future pipeline', 'caption' => ''],
                'table_3' => ['title' => 'Planned procurements', 'caption' => ''],
                'table_1' => ['title' => 'Procurements in progress', 'caption' => ''],
                'table_0' => ['title' => 'Procurements recently awarded', 'caption' => ''],
                'table_2' => ['title' => 'Dynamic Purchasing Systems currently open', 'caption' => ''],
                'table_5' => ['title' => 'Dynamic Market currently open', 'caption' => ''],
            ]));
        });

        $controller = static::getContainer()->get(\App\Controller\FrameworksController::class);
        $reflection = new \ReflectionClass($controller);
        $httpClientProperty = $reflection->getProperty('httpClient');
        $httpClientProperty->setAccessible(true);
        $httpClientProperty->setValue($controller, $this->mockHttpClient);

        $mockPagination = $this->createMock(\Strata\Frontend\Content\Pagination\PaginationInterface::class);
        $mockPagination->method('getTotalPages')->willReturn(1);
        $mockPagination->method('getTotalResults')->willReturn(0);

        $realCollection = new \Strata\Frontend\Content\PageCollection($mockPagination);

        $mockContentType = $this->createMock(\Strata\Frontend\ContentModel\ContentType::class);
        $mockContentModel = $this->createMock(\Strata\Frontend\ContentModel\ContentModel::class);
        $mockContentModel->method('getContentType')->willReturn($mockContentType);

        $mockSearchApi = $this->createMock(\Strata\Frontend\Cms\RestData::class);
        $mockSearchApi->method('getContentModel')->willReturn($mockContentModel);
        $mockSearchApi->method('getContentType')->willReturn($mockContentType);
        $mockSearchApi->method('list')->willReturn($realCollection);

        $searchApiProperty = $reflection->getProperty('searchApi');
        $searchApiProperty->setAccessible(true);
        $searchApiProperty->setValue($controller, $mockSearchApi);

        $this->client->request('GET', '/agreements/upcoming');

        $this->assertResponseIsSuccessful();
        $html = $this->client->getResponse()->getContent();

        $this->assertStringContainsString('Upcoming agreements overview', $html);
        $this->assertStringContainsString('Find upcoming procurements here.', $html);
    }

    /**
     * Tests that the framework suppliers endpoint renders successfully.
     */
    public function testSuppliersOnFrameworkRendersSuccessfully()
    {
        // 1. Build the exact data structure Twig expects
        $supplierData = [
            'supplier_id' => 123,
            'supplier_name' => 'Acme Test Supplier',
            'supplier_crp_url' => '',
            'live_frameworks' => [
                [
                    'title' => 'Test Framework',
                    'rm_number' => 'RM1234',
                    'status' => 'Live' // Setting this to Live bypasses the end_date.format() Twig crash!
                ]
            ]
        ];

        $mockContent = \App\Tests\App\Mock\CMSContentMockFactory::createMockContent($supplierData);
        $mockPage = $this->createMock(\Strata\Frontend\Content\Page::class);
        $mockPage->method('getContent')->willReturn($mockContent);

        // 2. Mock Pagination 
        $mockPagination = $this->createMock(\Strata\Frontend\Content\Pagination\PaginationInterface::class);
        $mockPagination->method('getTotalPages')->willReturn(1);
        $mockPagination->method('getTotalResults')->willReturn(1);

        // 3. Build Collection & Add Metadata
        $realCollection = new \Strata\Frontend\Content\PageCollection($mockPagination);
        $realCollection->addItem($mockPage);
        $realCollection->getMetadata()->add('framework_title', 'Test Framework Title');
        $realCollection->getMetadata()->add('framework_rm_number', 'RM1234');

        // 4. API Mocking
        $mockContentType = $this->createMock(\Strata\Frontend\ContentModel\ContentType::class);
        $mockContentModel = $this->createMock(\Strata\Frontend\ContentModel\ContentModel::class);
        $mockContentModel->method('getContentType')->willReturn($mockContentType);

        $mockRestData = $this->createMock(\Strata\Frontend\Cms\RestData::class);
        $mockRestData->method('getContentModel')->willReturn($mockContentModel);
        $mockRestData->method('list')->willReturn($realCollection);

        // Inject into container
        static::getContainer()->set('app.test.rest_data_api', $mockRestData);

        // 5. Dispatch Request (Check your routes.yaml if this URL varies!)
        $this->client->request('GET', '/agreements/RM1234/suppliers');

        // 6. Assertions
        $this->assertResponseIsSuccessful();
        $html = $this->client->getResponse()->getContent();
        
        $this->assertStringContainsString('Acme Test Supplier', $html);
        $this->assertStringContainsString('Test Framework Title', $html);
    }

    /**
     * Tests that the framework lot suppliers endpoint renders successfully.
     */
    public function testSuppliersOnLotRendersSuccessfully()
    {
        $supplierData = [
            'supplier_id' => 456,
            'supplier_name' => 'Lot Supplier',
            'supplier_trading_name' => 'Lot Trading Name',
            'supplier_contact_name' => 'Jane Doe',
            'supplier_contact_email' => 'jane@example.com',
        ];

        $mockContent = \App\Tests\App\Mock\CMSContentMockFactory::createMockContent($supplierData);
        $mockPage = $this->createMock(\Strata\Frontend\Content\Page::class);
        $mockPage->method('getContent')->willReturn($mockContent);

        $mockPagination = $this->createMock(\Strata\Frontend\Content\Pagination\PaginationInterface::class);
        $mockPagination->method('getTotalPages')->willReturn(1);
        $mockPagination->method('getTotalResults')->willReturn(1);

        $realCollection = new \Strata\Frontend\Content\PageCollection($mockPagination);
        $realCollection->addItem($mockPage);
        $realCollection->getMetadata()->add('framework_title', 'Test Framework Title');
        $realCollection->getMetadata()->add('framework_rm_number', 'RM1234');
        $realCollection->getMetadata()->add('lot_number', '1');
        $realCollection->getMetadata()->add('lot_title', 'Test Lot');
        $realCollection->getMetadata()->add('lot_description', 'Lot details');

        $mockContentType = $this->createMock(\Strata\Frontend\ContentModel\ContentType::class);
        $mockContentModel = $this->createMock(\Strata\Frontend\ContentModel\ContentModel::class);
        $mockContentModel->method('getContentType')->willReturn($mockContentType);

        $mockRestData = $this->createMock(\Strata\Frontend\Cms\RestData::class);
        $mockRestData->method('getContentModel')->willReturn($mockContentModel);
        $mockRestData->method('list')->willReturn($realCollection);

        static::getContainer()->set('app.test.rest_data_api', $mockRestData);

        $this->client->request('GET', '/agreements/RM1234:1/lot-suppliers/1');

        $this->assertResponseIsSuccessful();
        $html = $this->client->getResponse()->getContent();

        $this->assertStringContainsString('Lot 1: Test Lot', $html);
        $this->assertStringContainsString('Lot Trading Name', $html);
        $this->assertStringContainsString('Test Framework Title', $html);
        $this->assertStringContainsString('Download Supplier Contact Details', $html);
    }
}