<?php

declare(strict_types=1);

namespace App\Tests\App\Controller;

use Symfony\Component\HttpClient\Response\MockResponse;

class FrameworksControllerTest extends AbstractControllerTestCase
{
    /**
     * Tests that requests with Bot User-Agents are immediately rejected.
     */
    public function testListEndpointBlocksBotsAndThrowsAccessDenied()
    {
        $this->client->request('GET', '/agreements/1', [], [], [
            'HTTP_USER_AGENT' => 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)'
        ]);
        
        $this->assertResponseStatusCodeSame(403);
    }

    /**
     * Tests that legacy category slugs are automatically 302 redirected to their modern equivalents.
     */
    public function testListEndpointRedirectsOldCategorySlugs()
    {
        $this->client->request('GET', '/agreements/1', ['category' => 'utilities-fuels']);
        
        // Match the exact query string array wrapper generated by Symfony
        $this->assertResponseRedirects('/agreements?category%5B0%5D=Energy');
    }

    /**
     * Tests the hardcoded redirect for the CAS agreement.
     */
    public function testShowEndpointRedirectsCasAgreement()
    {
        $this->client->request('GET', '/agreements/RM6187_cas');
        
        $this->assertResponseRedirects('/agreements/RM6187');
    }

    /**
     * Tests that the framework show endpoint successfully renders the page using fixture data.
     */
    public function testShowEndpointRendersFrameworkSuccessfully()
    {
        // 1. Load and decode your raw JSON fixture
        // (Make sure the path matches where you put your fixtures folder!)
        $fixturePath = __DIR__ . '/../../Fixtures/frameworks_show.json';
        $fixtureJson = file_get_contents($fixturePath);
        $frameworkData = json_decode($fixtureJson, true);

        // 2. Pass the decoded array straight into our factory
        $mockContent = \App\Tests\App\Mock\CMSContentMockFactory::createMockContent($frameworkData);

        // 3. Mock the Page object to return our factory content
        $mockPage = $this->createMock(\Strata\Frontend\Content\Page::class);
        $mockPage->method('getContent')->willReturn($mockContent);

        // 4. Build the Mock Chain for the ContentModel (to prevent the null pointer errors)
        $mockContentType = $this->createMock(\Strata\Frontend\ContentModel\ContentType::class);
        $mockContentModel = $this->createMock(\Strata\Frontend\ContentModel\ContentModel::class);
        $mockContentModel->method('getContentType')->willReturn($mockContentType);

        // 5. Create the RestData mock
        $mockRestData = $this->createMock(\Strata\Frontend\Cms\RestData::class);
        $mockRestData->method('getContentModel')->willReturn($mockContentModel);
        
        // Note: Strata's default method for fetching a single page is getOne(). 
        // If your controller uses a different method name to fetch the agreement, update it here.
        $mockRestData->method('getOne')->willReturn($mockPage); 

        // 6. Inject the mock into the container
        static::getContainer()->set('app.test.rest_data_api', $mockRestData);

        // 7. Dispatch the request to the show endpoint for RM6184
        $this->client->request('GET', '/agreements/RM6184');

        // 8. Run your assertions
        $this->assertResponseIsSuccessful();
        
        // Assert that the page rendered the specific data from our fixture!
        $html = $this->client->getResponse()->getContent();
        
        $this->assertStringContainsString('RM6184', $html);
        $this->assertStringContainsString('Offsite Construction Solutions', $html);
        $this->assertStringContainsString('Standard framework', $html);
    }


  /**
     * Tests that the lot suppliers endpoint compiles data into a downloadable CSV attachment.
     */
    public function testSuppliersOnLotCsvGeneratesTextAttachment()
    {
        $supplierData = [
            'supplier_name'          => 'Acme Corp',
            'supplier_trading_name'  => 'Acme Trading',
            'supplier_contact_name'  => 'Wile E. Coyote',
            'supplier_contact_email' => 'wile@acme.com',
            'supplier_street'        => '123 Desert Road',
            'supplier_city'          => 'Canyon',
            'supplier_postcode'      => 'AC1 1ME'
        ];

        // 1. Create the content using our own factory
        $mockContent = \App\Tests\App\Mock\CMSContentMockFactory::createMockContent($supplierData);

        // 2. Create a mock of the strict Page class and return our factory content
        $mockPage = $this->createMock(\Strata\Frontend\Content\Page::class);
        $mockPage->method('getContent')->willReturn($mockContent);

        // 3. Create a mock Pagination object required by the collection constructor
        $mockPagination = $this->createMock(\Strata\Frontend\Content\Pagination\PaginationInterface::class);

        // 4. Instantiate the REAL PageCollection and use its native addItem() method
        $realCollection = new \Strata\Frontend\Content\PageCollection($mockPagination);
        $realCollection->addItem($mockPage);

        // 5. Build the Mock Chain for the ContentModel
        $mockContentType = $this->createMock(\Strata\Frontend\ContentModel\ContentType::class);
        $mockContentModel = $this->createMock(\Strata\Frontend\ContentModel\ContentModel::class);
        $mockContentModel->method('getContentType')->willReturn($mockContentType);

        // 6. Create a type-safe PHPUnit mock of RestData
        $mockRestData = $this->createMock(\Strata\Frontend\Cms\RestData::class);
        
        // 7. Stub the internal method calls so the controller doesn't hit a null pointer
        $mockRestData->method('getContentModel')->willReturn($mockContentModel);
        $mockRestData->method('list')->willReturn($realCollection);

        // 8. Inject the mock RestData into the test container
        static::getContainer()->set('app.test.rest_data_api', $mockRestData);

        // 9. Dispatch the CSV request
        $this->client->request('GET', '/agreements/RM123:1/lot-suppliers/csv');

        $this->assertResponseIsSuccessful();
        $this->assertResponseHeaderSame('Content-Type', 'text/plain; charset=UTF-8');
        $this->assertResponseHeaderSame('Content-Disposition', 'attachment; filename="RM123_Lot1.csv";');

        // Extract and verify contents
        $csvContent = $this->client->getResponse()->getContent();
        $this->assertStringContainsString('"Supplier Name","Trading Name"', $csvContent);
        $this->assertStringContainsString('"Acme Corp","Acme Trading"', $csvContent);
    }
}