# Travis CI (MIT License) configuration file
# @link https://travis-ci.org/
# @link https://github.com/jrfnl/make-phpcs-work-for-you/tree/master/travis-examples

# Only run on the following branches
branches:
  only:
    - development
    - preprod
    - master

# Declare project language
# @link http://about.travis-ci.org/docs/user/languages/php/
language: php

# Declare versions of PHP to use. Use one decimal max
# @link http://docs.travis-ci.com/user/build-configuration/
matrix:
  fast_finish: true
  include:
    - php: '7.3'
      env: SNIFF=1
    - php: '7.4'

before_install:
  - composer self-update;
  - composer install;

script:
  # Search for PHP syntax errors
  - vendor/bin/phplint
  # Run PHPCS
  - if [[ "$SNIFF" == "1" ]]; then vendor/bin/phpcs; fi
  # Run PHP Unit
  - bin/phpunit
  - bin/phpunit vendor/studio24/frontend/tests

notifications:
  on_success: never
  on_failure: always
