rollbar:
  access_token: '%env(ROLLBAR_ACCESS_TOKEN)%'
  environment: '%env(APP_ENV)%'
monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        nested:
            type: rotating_file
            max_files: 7
            path: "%kernel.logs_dir%/symfony.log"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        rollbar:
            type: service
            id: Rollbar\Monolog\Handler\RollbarHandler
