# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $appApiBaseUrl: '%env(APP_API_BASE_URL)%'
            $appBaseUrl: '%env(APP_BASE_URL)%'
            $searchApiBaseUrl: '%env(SEARCH_API_BASE_URL)%'
            $appCmsBaseUrl: '%env(APP_CMS_BASE_URL)%'
            $salesforceWebToCaseUrl: '%env(SALESFORCE_WEB_TO_CASE_URL)%'
            $sfRmCaseId: '%env(SF_RM_CASE_ID)%'
            $documentHandlingPath: '%env(documentHanding_path)%'
            $documentHandlingKey: '%env(documentHanding_key)%'
            $documentHandlingEndpoint: '%env(documentHanding_endpoint)%'
            $qualtricsApiToken: '%env(QUALTRICS_API_TOKEN)%'
            $qualtricsSurveyId: '%env(QUALTRICS_SURVEY_ID)%'
            $appEnv: '%env(APP_ENV)%'
            $orgIdProd: '%env(ORG_ID_PROD)%'
            $orgIdTest: '%env(ORG_ID_TEST)%'
            $pardotUrls:
                contact: '%env(default::PARDOT_EMAIL_FORM_HANDLER_URL)%'
                people: '%env(default::PARDOT_EMAIL_FORM_HANDLER_PEOPLE_URL)%'
                corpsol: '%env(default::PARDOT_EMAIL_FORM_HANDLER_CORPORATE_URL)%'
                buildings: '%env(default::PARDOT_EMAIL_FORM_HANDLER_BUILDINGS_URL)%'
                tech: '%env(default::PARDOT_EMAIL_FORM_HANDLER_TECH_URL)%'
                guide: '%env(default::PARDOT_EMAIL_FORM_HANDLER_GUIDE_URL)%'
                cnz: '%env(default::PARDOT_EMAIL_FORM_HANDLER_CNZ_URL)%'
                digitransformation: '%env(default::PARDOT_EMAIL_FORM_HANDLER_DIGITRANS_URL)%'
                digilg: '%env(default::PARDOT_EMAIL_FORM_HANDLER_DIGILG_URL)%'
                diginhs: '%env(default::PARDOT_EMAIL_FORM_HANDLER_DIGINHS_URL)%'
                estates: '%env(default::PARDOT_EMAIL_FORM_HANDLER_ESTATES_URL)%'
                covidrecovery: '%env(default::PARDOT_EMAIL_FORM_HANDLER_COVIDRECOVERY_URL)%'
                agg: '%env(default::PARDOT_EMAIL_FORM_HANDLER_AGG_URL)%'
                event: '%env(default::PARDOT_EMAIL_FORM_HANDLER_EVENT_URL)%'
                construction: '%env(default::PARDOT_EMAIL_FORM_HANDLER_CONSTRUCTION_URL)%'
                fleet: '%env(default::PARDOT_EMAIL_FORM_HANDLER_FLEET_URL)%'
                tepas: '%env(default::PARDOT_EMAIL_FORM_HANDLER_TEPAS_URL)%'
                nhswa: '%env(default::PARDOT_EMAIL_FORM_HANDLER_NHSWA_URL)%'
                mou: '%env(default::PARDOT_EMAIL_FORM_HANDLER_MOU_URL)%'
                cyber: '%env(default::PARDOT_EMAIL_FORM_HANDLER_CYBER_URL)%'
                newsletter: '%env(default::PARDOT_EMAIL_FORM_HANDLER_NEWSLETTER_URL)%'
                lg: '%env(default::PARDOT_EMAIL_FORM_HANDLER_LG_URL)%'
                nhs: '%env(default::PARDOT_EMAIL_FORM_HANDLER_NHS_URL)%'
                whitepaper: '%env(default::PARDOT_EMAIL_FORM_HANDLER_WHITEPAPER_URL)%'
                webinar: '%env(default::PARDOT_EMAIL_FORM_HANDLER_WEBINAR_URL)%'
                digitalbrochure: '%env(default::PARDOT_EMAIL_FORM_HANDLER_DB_URL)%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Register Frontend Twig helpers
    Strata\Frontend\Twig\FrontendExtension:
        tags: ['twig.extension']

    # Response listener
    # @todo remove this in Symfony 4.3 - see https://symfony.com/blog/new-in-symfony-4-3-automatic-search-engine-protection
    App\EventListener\ResponseListener:
        tags:
            - { name: kernel.event_listener, event: kernel.response }

    # Rollbar Monolog handler, referenced by id from config/packages/*/monolog.yaml
    app.rollbar_handler:
        class: Monolog\Handler\RollbarHandler
        factory: ['App\Factory\RollbarHandlerFactory', 'create']
        arguments:
            $accessToken: '%env(ROLLBAR_ACCESS_TOKEN)%'
            $environment: '%env(APP_ENV)%'

     # Define the Wordpress API Service
    Strata\Frontend\Cms\Wordpress:
        public: true # Important for testing!
        lazy: true
        arguments:
            $baseUrl: '%env(APP_API_BASE_URL)%'
            $contentModel: '@Strata\Frontend\ContentModel\ContentModel'
        calls:
            - [setContentType, ['page']]

    # Update PageController to receive it
    App\Controller\PageController:
        bind:
            $redirectionApi: '@app.api.redirection'
            $api: '@Strata\Frontend\Cms\Wordpress' # Injects the service above

    # Define a shared ContentModel service (used by multiple APIs)
    Strata\Frontend\ContentModel\ContentModel:
        arguments: ['%kernel.project_dir%/config/content/content-model.yaml']

    # Define the Redirection API specifically
    app.api.redirection:
        class: Strata\Frontend\Cms\RestData
        public: true
        arguments:
            $baseUrl: '%env(APP_API_BASE_URL)%'
            $contentModel: '@Strata\Frontend\ContentModel\ContentModel'
        calls:
            - [setContentType, ['redirections']]

    # Allow tests to mock this service
    App\Service\GuideJourneyService:
        public: true
        # Autowiring is enabled by default at the top of the file,
        # so you don't need to define arguments here unless they are special.
