digital_brochure_file:
  type: document
form_introduction:
  type: richtext
link_text:
  type: text
campaign_code:
  type: text
description:
  type: text
digital_brochure_url:
  type: text
digital_brochure_url_text:
  type: text