downloadable_resources_url:
  type: text
downloadable_resources_url_text:
  type: text
downloadable_resources_file:
  type: document
downloadable_resources_file_text:
  type: text
downloadable_type:
  type: text
prompt_text:
  type: text
download_confirmation_msg:
  type: text
embed_video:
  type: text
form_introduction:
  type: text
link_text:
  type: text
description:
  type: text
campaign_code:
  type: text
