supplier_name:
  type: text
supplier_id:
  type: number
supplier_phone:
  type: text
supplier_street:
  type: text
supplier_city:
  type: text
supplier_postcode:
  type: text
supplier_country:
  type: text
supplier_email:
  type: text
supplier_website:
  type: text
live_frameworks:
  type: array
  content_fields:
    title:
      type: text
    rm_number:
      type: text
    status:
      type: text
    end_date:
      type: date
