supplier_name:
  type: text
supplier_id:
  type: number
contact_email:
  type: text
live_frameworks:
  type: array
  content_fields:
    title:
      type: text
    rm_number:
      type: text
    status:
      type: text
    end_date:
      type: date
