meta:
  type: array
  content_fields:
    total_results:
      type: number
    intro_text:
      type: text
glossaries:
  type: array
  content_fields:
    term:
      type: text
    meaning:
      type: text