meta:
  type: array
  content_fields:
    total_results:
      type: number
    intro_text:
      type: text
glossaries:
  type: array
  content_fields:
    term:
      type: text
    meaning:
      type: text
    keyword:
      type: array
      content_fields:
        searchable_keyword:
          type: text