featured_media:
  type: image
form_introduction:
  type: richtext
additional_text:
  type: text
webinar_video:
  type: text
link_text:
  type: text
campaign_code:
  type: text
description:
  type: text
